module Version

include "runtime/unsafe/wasmi32"
include "runtime/dataStructures"
from DataStructures use { newInt32 }

include "./api/version"
from Version use { major, minor, patch }

@unsafe
provide let major = () => {
  WasmI32.toGrain(newInt32(major())): Int32
}

@unsafe
provide let minor = () => {
  WasmI32.toGrain(newInt32(minor())): Int32
}

@unsafe
provide let patch = () => {
  WasmI32.toGrain(newInt32(patch())): Int32
}
