module Wasi

provide foreign wasm config_add_environment_variable: (
  WasmI64,
  WasmI32,
  WasmI32,
  WasmI32,
  WasmI32,
) -> Void as configAddEnvironmentVariable from "lunatic::wasi"
provide foreign wasm config_add_command_line_argument: (
  WasmI64,
  WasmI32,
  WasmI32,
) -> Void as configAddCommandLineArgument from "lunatic::wasi"
provide foreign wasm config_preopen_dir: (
  WasmI64,
  WasmI32,
  WasmI32,
) -> Void as configPreopenDir from "lunatic::wasi"
