module Version

include "lunatic"
from Lunatic use { module Version }

let semverString = (major, minor, patch) => {
  let (major, minor, patch) = (
    toString(major),
    toString(minor),
    toString(patch),
  )
  "v" ++ major ++ "." ++ minor ++ "." ++ patch
}

provide let _start = () => {
  print(
    "Hello from Lunatic " ++
    semverString(Version.major(), Version.minor(), Version.patch())
  )
}
