module Version

from "runtime/unsafe/wasmi32" include WasmI32
from "runtime/dataStructures" include DataStructures
use DataStructures.{ newInt32 }

from "./api/version.gr" include Version
use Version.{ major, minor, patch }

@unsafe
provide let major = () => {
  WasmI32.toGrain(newInt32(major())): Int32
}

@unsafe
provide let minor = () => {
  WasmI32.toGrain(newInt32(minor())): Int32
}

@unsafe
provide let patch = () => {
  WasmI32.toGrain(newInt32(patch())): Int32
}
